# Generated by Django 4.2.13 on 2026-07-01 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'événement", max_length=200)),
                ('description', models.TextField(help_text="Description détaillée de l'événement")),
                ('date_start', models.DateTimeField(help_text='Date et heure de début')),
                ('date_end', models.DateTimeField(help_text='Date et heure de fin')),
                ('location', models.CharField(help_text="Lieu de l'événement", max_length=300)),
                ('max_capacity', models.IntegerField(help_text='Nombre maximum de participants', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='draft', help_text="Statut de l'événement", max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Image de couverture', null=True, upload_to='event_images/')),
                ('category', models.CharField(choices=[('cultural', 'Culturel'), ('sports', 'Sportif'), ('professional', 'Professionnel'), ('other', 'Autre')], default='other', help_text="Catégorie de l'événement", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'events_event',
                'ordering': ['-date_start'],
            },
        ),
    ]
