# Generated by Django 4.2.13 on 2026-07-01 01:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('student', 'Étudiant')], help_text='Type de billet', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix du billet', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quota', models.IntegerField(help_text='Nombre de billets disponibles', validators=[django.core.validators.MinValueValidator(1)])),
                ('sold', models.IntegerField(default=0, help_text='Nombre de billets vendus', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Événement associé', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'verbose_name': 'Type de billet',
                'verbose_name_plural': 'Types de billets',
                'db_table': 'tickets_tickettype',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(editable=False, help_text='Code unique du billet', max_length=100, unique=True)),
                ('quantity', models.IntegerField(default=1, help_text='Nombre de billets réservés', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='pending', help_text='Statut de la réservation', max_length=20)),
                ('is_cancelled', models.BooleanField(default=False, help_text='Réservation annulée')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Prix total de la réservation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('refunded', 'Remboursé')], default='pending', help_text='Statut du paiement', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Événement réservé', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='events.event')),
                ('ticket_type', models.ForeignKey(help_text='Type de billet réservé', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tickets.tickettype')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'tickets_reservation',
                'ordering': ['-created_at'],
            },
        ),
    ]
