# Generated by Django 4.2.13 on 2026-07-01 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur qui a réservé', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'type_name'], name='tickets_tic_event_i_459a76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('event', 'type_name')},
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'event'], name='tickets_res_user_id_5eeb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['event', 'status'], name='tickets_res_event_i_abef6c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['ticket_code'], name='tickets_res_ticket__4ff0d6_idx'),
        ),
    ]
