# Generated by Django 4.2.13 on 2026-07-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration du lock temporaire", null=True),
        ),
    ]
