# Generated by Django 4.2.13 on 2026-07-01 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('event_published', 'Événement publié'), ('event_cancelled', 'Événement annulé'), ('event_updated', 'Événement mis à jour'), ('reservation_confirmed', 'Réservation confirmée'), ('reservation_cancelled', 'Réservation annulée'), ('seats_updated', 'Places mises à jour')], help_text='Type de notification', max_length=50)),
                ('title', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('message', models.TextField(help_text='Contenu de la notification')),
                ('is_read', models.BooleanField(default=False, help_text='Notification lue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, help_text='Événement concerné', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
